name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
        python-version: ["3.10", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py
      - name: Install dependencies
        env:
          INSTALL_PYQT6: ${{ startsWith(matrix.os, 'macos') && '1' || '0' }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
      - name: Setup display
        if: runner.os == 'Linux'
        run: |
          export DISPLAY=:0.0
          Xvfb :0 -screen 0 640x480x24 &
      - name: Run tests
        run: |
          cd tests
          pytest
      - name: Upload failure images
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-images-${{ matrix.os }}-py${{ matrix.python-version }}
          path: tests/failure/
